import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import fs from "fs";
import path from "path";

/**
 * Resolve the app version at config time. Source of truth (in order):
 *   1. `src/version.ts` at repo root — generated by `scripts/update-version.sh`,
 *      includes git hash + commit count (e.g. `0.1.5+34.5bdc6fa`).
 *   2. Root `package.json` — bare semver fallback for fresh checkouts that
 *      haven't run the version script yet.
 *   3. The literal string "unknown" — last-resort guard so the build never
 *      fails because of a version lookup.
 *
 * The values are injected as compile-time globals via Vite's `define`:
 *   - `__APP_VERSION__`       — short semver (e.g. `0.1.5`)
 *   - `__APP_FULL_VERSION__`  — semver + commits + hash (e.g. `0.1.5+34.5bdc6fa`)
 *
 * Types are declared in `src/vite-env.d.ts`.
 */
function resolveVersion(): { version: string; fullVersion: string } {
  const versionTsPath = path.resolve(__dirname, "../src/version.ts");
  const pkgJsonPath = path.resolve(__dirname, "../package.json");

  try {
    if (fs.existsSync(versionTsPath)) {
      const src = fs.readFileSync(versionTsPath, "utf-8");
      const versionMatch = src.match(/export const VERSION = "([^"]+)"/);
      const fullVersionMatch = src.match(/export const FULL_VERSION = "([^"]+)"/);
      if (versionMatch && fullVersionMatch) {
        return { version: versionMatch[1], fullVersion: fullVersionMatch[1] };
      }
    }
  } catch {
    // Fall through to package.json
  }

  try {
    const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf-8"));
    if (typeof pkg.version === "string") {
      return { version: pkg.version, fullVersion: pkg.version };
    }
  } catch {
    // Fall through to "unknown"
  }

  return { version: "unknown", fullVersion: "unknown" };
}

const { version, fullVersion } = resolveVersion();

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  define: {
    __APP_VERSION__: JSON.stringify(version),
    __APP_FULL_VERSION__: JSON.stringify(fullVersion),
  },
  server: {
    port: 5173,
    proxy: {
      "/api": {
        target: "http://localhost:3001",
        changeOrigin: true,
      },
    },
  },
});
