#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Read base version from package.json
BASE_VERSION=$(node -p "require('$REPO_ROOT/package.json').version")

# Get short hash
GIT_HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Get commit count since last v* tag, or total commits if no tags
if git -C "$REPO_ROOT" describe --tags --match "v*" --abbrev=0 >/dev/null 2>&1; then
  LAST_TAG=$(git -C "$REPO_ROOT" describe --tags --match "v*" --abbrev=0)
  GIT_COMMITS=$(git -C "$REPO_ROOT" rev-list "${LAST_TAG}..HEAD" --count)
else
  GIT_COMMITS=$(git -C "$REPO_ROOT" rev-list HEAD --count 2>/dev/null || echo "0")
fi

# Build full version string
if [ "$GIT_COMMITS" -eq 0 ]; then
  FULL_VERSION="$BASE_VERSION"
else
  FULL_VERSION="${BASE_VERSION}+${GIT_COMMITS}.${GIT_HASH}"
fi

# Generate src/version.ts
cat > "$REPO_ROOT/src/version.ts" <<EOF
// Auto-generated by scripts/update-version.sh — do not edit
export const VERSION = "${BASE_VERSION}";
export const GIT_HASH = "${GIT_HASH}";
export const GIT_COMMITS = ${GIT_COMMITS};
export const FULL_VERSION = "${FULL_VERSION}";
EOF

echo "Version updated: $FULL_VERSION"
